language: python
python:
  - "3.5"
addons:
  apt:
    sources:
    - graphviz
install:
  - pip install graphviz
  - pip install codecov
  - pip install codacy-coverage
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml 
script:
  - coverage run --omit="*/test*" -m unittest discover -s tests/ -v
