language: python
python:
  - "3.5"
install:
  - pip install codecov
  - pip install codacy-coverage
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml 
script:
  - coverage run --omit="*/test*" -m unittest discover -s tests/ -v
